language: python
before_install:
#using miniconda to get around Travis scipy problems
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="/home/travis/miniconda/bin:$PATH"
- conda update --yes conda
- conda install --yes python="$TRAVIS_PYTHON_VERSION" numpy scipy nose
#Install BioNetGen for PySB
- wget "http://www.csb.pitt.edu/Faculty/Faeder/?smd_process_download=1&download_id=142"
    -O BioNetGen-2.2.6-stable.tar.gz
- tar xzf BioNetGen-2.2.6-stable.tar.gz
- export BNGPATH=`pwd`/BioNetGen-2.2.6-stable
install:
  - pip install .
  - pip install https://github.com/LoLab-VU/pysb/archive/master.zip
  - pip install -r requirements.txt
  #Install these to enable plotting in examples
  - pip install seaborn
  - pip install matplotlib
# command to run tests
script:
  nosetests
#command to run examples
  python pydream/examples/corm/example_sample_corm_with_dream.py
  python pydream/examples/mixturemodel/mixturemodel.py
  python pydream/examples/ndim_gaussian/dream_ex_ndim_gaussian.py
  python pydream/examples/robertson/example_sample_robertson_with_dream.py

